services:
  - type: web
    name: pharmacy-app
    env: docker
    rootDir: web  # <-- THIS LINE IS ESSENTIAL
    plan: free

    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan key:generate
      php artisan migrate --force

    startCommand: php -S 0.0.0.0:10000 -t public

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: laravel
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: 
