services:
  - type: web
    name: pharmacy-app
    env: docker
    plan: free
    dockerfilePath: web/Dockerfile
    region: oregon
    buildCommand: |
      composer install --no-dev --optimize-autoloader
    startCommand: |
      php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        value: base64:5UaBlYeeBfksiABvOPR8IvXgzwRbatN1fuWFexAnQpY=
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: laravel
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: 
